<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ini</string>
	</array>
	<key>name</key>
	<string>CAN/UDS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#pidsRX2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pidsRX3</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pidsTX4</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pidsTX5</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pidsTX6</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pidsTX7</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ac4</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#ac5</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#long</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#longTX</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#continue</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\/\/.+$</string>
			<key>name</key>
			<string>comment.line.ini</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^RX,7[0-9A-F]{2},8</string>
			<key>name</key>
			<string>storage.type.ini</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^TX,7[0-9A-F]{2},8</string>
			<key>name</key>
			<string>entity.name.function.ini</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s+\n</string>
			<key>name</key>
			<string>invalid.illegal.ini</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>ac4</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ini</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^[RT]X,7[0-9A-F]{2},8,)(0)(4) ([26]F) (([0-9A-F]{2} ){2})([0-9A-F]{2}) (([0-9A-F]{2} ){2}[0-9A-F]{2})</string>
		</dict>
		<key>ac5</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ini</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^[RT]X,7[0-9A-F]{2},8,)(0)(5) ([26]F) (([0-9A-F]{2} ){2})(03) ([0-9A-F]{2})(( [0-9A-F]{2}){2})</string>
		</dict>
		<key>continue</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^RX,7[0-9A-F]{2},8,)(30( [0-9A-F]{2}){7})</string>
		</dict>
		<key>long</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^TX,7[0-9A-F]{2},8,)(2[0-9A-F])</string>
		</dict>
		<key>longTX</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^RX,7[0-9A-F]{2},8,)(10( [0-9A-F]{2}){2})(( [0-9A-F]{2}){5})</string>
		</dict>
		<key>pidsRX2</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ini</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^RX,7[0-9A-F]{2},8,)(02 21) ([0-9A-F]{2})(( [0-9A-F]{2}){5})</string>
		</dict>
		<key>pidsRX3</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ini</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^RX,7[0-9A-F]{2},8,)(03 22) (([0-9A-F]{2} ){2})(([0-9A-F]{2} ){3}[0-9A-F]{2})</string>
		</dict>
		<key>pidsTX4</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ini</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^TX,7[0-9A-F]{2},8,)(0)(4) (62) (([0-9A-F]{2} ){2})([0-9A-F]{2}) (([0-9A-F]{2} ){2}[0-9A-F]{2})</string>
		</dict>
		<key>pidsTX5</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ini</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^TX,7[0-9A-F]{2},8,)(0)(5) (62) (([0-9A-F]{2} ){2})(([0-9A-F]{2} ){2})([0-9A-F]{2} [0-9A-F]{2})</string>
		</dict>
		<key>pidsTX6</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ini</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^TX,7[0-9A-F]{2},8,)(0)(6) (62) (([0-9A-F]{2} ){2})(([0-9A-F]{2} ){3})([0-9A-F]{2})</string>
		</dict>
		<key>pidsTX7</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.other.ini</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control.ini</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.ini</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=^TX,7[0-9A-F]{2},8,)(0)(7) (62) (([0-9A-F]{2} ){2})(([0-9A-F]{2} ){3}[0-9A-F]{2})</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ini</string>
	<key>uuid</key>
	<string>b8ef7405-34e3-40ca-bb55-17b18f8247bd</string>
</dict>
</plist>
